"""Shared constants for training components."""

from __future__ import annotations

CATBOOST_KEY = "catboost"
XGBOOST_KEY = "xgboost"
LIGHTGBM_KEY = "lightgbm"

RANDOM_FOREST_KEY = "rf"
GRADIENT_BOOSTING_KEY = "gbr"
HIST_GRADIENT_BOOSTING_KEY = "hgbt"
DECISION_TREE_KEY = "dt"
KNN_KEY = "knn"
SVR_KEY = "svr"
LINEAR_KEY = "linear"
RIDGE_KEY = "ridge"
LASSO_KEY = "lasso"
ELASTICNET_KEY = "elasticnet"

TREE_BASED_MODELS = {
    RANDOM_FOREST_KEY,
    GRADIENT_BOOSTING_KEY,
    HIST_GRADIENT_BOOSTING_KEY,
    XGBOOST_KEY,
    LIGHTGBM_KEY,
    CATBOOST_KEY,
    DECISION_TREE_KEY,
}

GPU_FRIENDLY_MODELS = {CATBOOST_KEY, XGBOOST_KEY, LIGHTGBM_KEY}

DEFAULT_TUNING_SPLIT_FRACTION = 0.8

__all__ = [
    "CATBOOST_KEY",
    "XGBOOST_KEY",
    "LIGHTGBM_KEY",
    "RANDOM_FOREST_KEY",
    "GRADIENT_BOOSTING_KEY",
    "HIST_GRADIENT_BOOSTING_KEY",
    "DECISION_TREE_KEY",
    "KNN_KEY",
    "SVR_KEY",
    "LINEAR_KEY",
    "RIDGE_KEY",
    "LASSO_KEY",
    "ELASTICNET_KEY",
    "TREE_BASED_MODELS",
    "GPU_FRIENDLY_MODELS",
    "DEFAULT_TUNING_SPLIT_FRACTION",
]
